---
- hosts: localhost
  connection: local
  become: no
  roles:
    - { role: digitalocean, tags: [digitalocean] }
  tasks:
    - pause:
        seconds: 3 # wait for droplet to be ready

- hosts: do_droplet_in_memory
  gather_facts: false
  become: no
  tasks:
    - block:
      - local_action: shell cat ~/.ssh/known_hosts | grep -qF {{ ansible_ssh_host }}
        register: known_hosts_exists
        ignore_errors: yes
      - local_action: shell ssh-keyscan {{ ansible_ssh_host }} >> ~/.ssh/known_hosts
        when: known_hosts_exists.rc != 0
      tags: ssh-keyscan

- hosts: do_droplet_in_memory
  name: Test Connection and Determine Remote User
  gather_facts: false
  roles:
    - { role: connection, tags: [connection] }
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - local_python_interpreter: "{{ ansible_playbook_python }}"

- hosts: do_droplet_in_memory
  gather_facts: no
  become: no
  roles:
    - { role: python-raw }

- hosts: do_droplet_in_memory
  become: no
  gather_facts: true
  tasks:
    - name: Get local machine's IP address
      set_fact:
        local_machine_ip: "{{ ansible_env['SSH_CLIENT'].split() | first }}"
  vars:
    - ansible_python_interpreter: /usr/bin/python3

- hosts: do_droplet_in_memory
  become: yes
  gather_facts: true
  roles:
    - { role: swapfile, tags: [swapfile] }
    - { role: fail2ban, tags: [fail2ban] }
    - { role: ufw, tags: [ufw] }
    - { role: ntp, tags: [ntp] }
    - { role: users, tags: [users] }
    - { role: unattended-upgrades, tags: [unattended-upgrades] }
    - { role: sshd, tags: [sshd] }
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - fail2ban_ip_whitelist: "{{ local_machine_ip }}"

- hosts: do_droplet_in_memory
  become: yes
  vars_prompt:
    - name: install_lemp
      prompt: Do you want to install the LEMP stack (y/n)?
      private: no
  tasks:
    - include: tasks/lemp.yml
      when: install_lemp == 'y'